### ISSUE TITLE
我想问下爬的页面怎么组件的

### ISSUE THREAD

**Issue by neal1991** [ccforward/cc#46]
把页面的数据爬下来难道还是自己再重新拼接数据的嘛

**Comment by ccforward** [comment]
@neal1991  

爬的不是页面的数据 而是爬取的APP的接口
APP的接口返回的是json格式的数据
爬下来后自己存储
然后再拼接已经存储好的数据

**Comment by neal1991** [comment]
你这样不会很麻烦嘛，需要一个个页面去拼接，还是说大多数页面可以用统一的方式去拼接

**Comment by ccforward** [comment]
@neal1991 

前端页面因为是用的Vue.js做的  
因为做了组件化，所以页面上很多内容复用组件就行了

后端数据接口就根据页面的需要一个一个写的，从不同的表里面查出数据再拼成json返回
